# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'IdeaMe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IdeaMe
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'IdeaMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'IdeaMe-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IdeaMe-tvOS

  target 'IdeaMe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
